Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RequestReferer:
  Enabled: false

Metrics/LineLength:
  Max: 140
  AllowHeredoc: true
  AllowURI: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Alias:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/MessageExpectation:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/BeforeAfterAll:
  Description: Check that before/after(:all) isn't being used.
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
